eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: spring-client
  boot:
    admin:
      client:
        url: http://localhost:8760
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS