spring:
  application:
    name: service-feign
  boot:
    admin:
      client:
        url: http://localhost:8760
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:  port: 8765